vdoestimator.c: rename uds.h to indexer.h
dm-vdo/vdoestimator pull request #29
Opened 2024-02-29 21:45 UTC by bgurney-rh

Related: #28

2024-02-29 22:17 UTC, jwieleRH requested changes
Please re-alphabetize the includes. Thanks!

2024-03-01 02:15 UTC, drckeefe commented
PR works for me, thanks

2024-03-01 17:09 UTC, bgurney-rh commented
Amended commit to add "indexer.h" in alphabetical order.

2024-03-01 19:14 UTC, jwieleRH approved these changes

2024-03-01 19:15 UTC, merged